services: 
  backend:
    build: ./Back-End
    container_name: weather-backend
    ports:
      - "8000:8000"
    env_file:
      - ./Back-End/.env
    restart: unless-stopped

  frontend:
    build: ./Front-End
    container_name: weather-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped